// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Soat.Eleven.Pedidos.Tests._0_BDD.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CriacaoDePedidoFeature : object, Xunit.IClassFixture<CriacaoDePedidoFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CriacaoPedido.feature"
#line hidden
        
        public CriacaoDePedidoFeature(CriacaoDePedidoFeature.FixtureData fixtureData, Soat_Eleven_Pedidos_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "0 - BDD/Features", "Criação de Pedido", "    Como um cliente do fast food\r\n    Eu quero criar um pedido com itens\r\n    Par" +
                    "a que eu possa realizar minha compra", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Criar um pedido com sucesso")]
        [Xunit.TraitAttribute("FeatureTitle", "Criação de Pedido")]
        [Xunit.TraitAttribute("Description", "Criar um pedido com sucesso")]
        public void CriarUmPedidoComSucesso()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Criar um pedido com sucesso", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 7
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
    testRunner.Given("que eu tenho um token de atendimento válido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 9
    testRunner.And("que eu tenho um cliente identificado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "ProdutoId",
                            "Quantidade",
                            "PrecoUnitario",
                            "DescontoUnitario"});
                table1.AddRow(new string[] {
                            "11111111-1111-1111-1111-111111111111",
                            "2",
                            "25.00",
                            "0.00"});
                table1.AddRow(new string[] {
                            "22222222-2222-2222-2222-222222222222",
                            "1",
                            "15.00",
                            "2.50"});
#line 10
    testRunner.And("que eu tenho os seguintes itens no pedido:", ((string)(null)), table1, "E ");
#line hidden
#line 14
    testRunner.When("eu criar o pedido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 15
    testRunner.Then("o pedido deve ser criado com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 16
    testRunner.And("o pedido deve ter status \"Pendente\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 17
    testRunner.And("o pedido deve ter uma senha gerada", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 18
    testRunner.And("o pedido deve conter 2 itens", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Criar um pedido sem cliente identificado")]
        [Xunit.TraitAttribute("FeatureTitle", "Criação de Pedido")]
        [Xunit.TraitAttribute("Description", "Criar um pedido sem cliente identificado")]
        public void CriarUmPedidoSemClienteIdentificado()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Criar um pedido sem cliente identificado", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 20
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 21
    testRunner.Given("que eu tenho um token de atendimento válido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 22
    testRunner.And("que eu não tenho um cliente identificado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "ProdutoId",
                            "Quantidade",
                            "PrecoUnitario",
                            "DescontoUnitario"});
                table2.AddRow(new string[] {
                            "11111111-1111-1111-1111-111111111111",
                            "1",
                            "30.00",
                            "0.00"});
#line 23
    testRunner.And("que eu tenho os seguintes itens no pedido:", ((string)(null)), table2, "E ");
#line hidden
#line 26
    testRunner.When("eu criar o pedido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 27
    testRunner.Then("o pedido deve ser criado com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 28
    testRunner.And("o pedido deve ter status \"Pendente\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 29
    testRunner.And("o pedido deve ter uma senha gerada", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 30
    testRunner.And("o cliente do pedido deve ser nulo", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Criar um pedido com múltiplos itens do mesmo produto")]
        [Xunit.TraitAttribute("FeatureTitle", "Criação de Pedido")]
        [Xunit.TraitAttribute("Description", "Criar um pedido com múltiplos itens do mesmo produto")]
        public void CriarUmPedidoComMultiplosItensDoMesmoProduto()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Criar um pedido com múltiplos itens do mesmo produto", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 32
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 33
    testRunner.Given("que eu tenho um token de atendimento válido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 34
    testRunner.And("que eu tenho um cliente identificado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "ProdutoId",
                            "Quantidade",
                            "PrecoUnitario",
                            "DescontoUnitario"});
                table3.AddRow(new string[] {
                            "33333333-3333-3333-3333-333333333333",
                            "5",
                            "10.00",
                            "1.00"});
#line 35
    testRunner.And("que eu tenho os seguintes itens no pedido:", ((string)(null)), table3, "E ");
#line hidden
#line 38
    testRunner.When("eu criar o pedido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 39
    testRunner.Then("o pedido deve ser criado com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 40
    testRunner.And("o pedido deve conter 1 itens", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 41
    testRunner.And("o total de itens no pedido deve ser 5", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Criar um pedido com desconto")]
        [Xunit.TraitAttribute("FeatureTitle", "Criação de Pedido")]
        [Xunit.TraitAttribute("Description", "Criar um pedido com desconto")]
        public void CriarUmPedidoComDesconto()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Criar um pedido com desconto", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 43
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 44
    testRunner.Given("que eu tenho um token de atendimento válido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 45
    testRunner.And("que eu tenho um cliente identificado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 46
    testRunner.And("que o pedido tem subtotal de 100.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 47
    testRunner.And("que o pedido tem desconto de 10.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 48
    testRunner.And("que o pedido tem total de 90.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "ProdutoId",
                            "Quantidade",
                            "PrecoUnitario",
                            "DescontoUnitario"});
                table4.AddRow(new string[] {
                            "44444444-4444-4444-4444-444444444444",
                            "2",
                            "50.00",
                            "5.00"});
#line 49
    testRunner.And("que eu tenho os seguintes itens no pedido:", ((string)(null)), table4, "E ");
#line hidden
#line 52
    testRunner.When("eu criar o pedido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 53
    testRunner.Then("o pedido deve ser criado com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 54
    testRunner.And("o subtotal do pedido deve ser 100.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 55
    testRunner.And("o desconto do pedido deve ser 10.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 56
    testRunner.And("o total do pedido deve ser 90.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                CriacaoDePedidoFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                CriacaoDePedidoFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
